DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users(
id VARCHAR(60) PRIMARY KEY NOT NULL,
email VARCHAR(60) NOT NULL,
password VARCHAR(30) NOT NULL,
refreshToken TEXT NULL,
create_at TIMESTAMP NOT NULL DEFAULT NOW()
)